### ISSUE TITLE
model = load_model(NeuralNetLoc)

### ISSUE THREAD

**Issue by ziqianwang9** [ealiotta/diffnet#1]
This my input command(python 3): 
python /Users/macbook/Downloads/diffnet-master/comed/applyDiffNet.py  /Users/macbook/Downloads/diffnet-master/pretrained_models/ /Users/macbook/Downloads/diffnet-master/test_data_3dir/  /Users/macbook/Downloads/diffnet-master/output/

Here is the problem:
Using TensorFlow backend.
Found 180 x 180 x 15 image with 3 directions (+b0 image)
Traceback (most recent call last):
  File "/Users/ziqianwanglive.cn/Downloads/diffnet-master/comed/applyDiffNet.py", line 75, in <module>
    model = load_model(NeuralNetLoc)
  File "/Users/macbook/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 184, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/Users/macbook/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 178, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/Users/macbook/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/Users/macbook/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 109, in deserialize
    printable_module_name='layer')
  File "/Users/macbook/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 362, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/Users/macbook/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 325, in class_and_config_for_serialized_keras_object
    for key, item in cls_config.items():
AttributeError: 'list' object has no attribute 'items'

**Comment by ealiotta** [comment]
It seems like this is likely due to the installed versions of keras/tensorflow: https://github.com/tensorflow/tensorflow/issues/35934

I am not entirely sure which versions are/are not compatible, but i am not seeing this issue with the following versions:

<img width="537" alt="Screen Shot 2020-06-29 at 11 30 32 AM" src="https://user-images.githubusercontent.com/18537920/86025282-05e4cf80-b9fc-11ea-925f-562a68099abe.png">
<img width="537" alt="Screen Shot 2020-06-29 at 11 30 48 AM" src="https://user-images.githubusercontent.com/18537920/86025292-08dfc000-b9fc-11ea-923a-9b50c55daa1f.png">

Since it looks like you are using anaconda, you can check your versions using: "conda list tensorflow" and "conda list keras"

**Comment by ziqianwang9** [comment]
Thank you for your reply. Following is my tensor flow version


(base) ziqianwanglive.cn@11:~$ conda list keras
# packages in environment at /Users/ziqianwanglive.cn/opt/anaconda3:
#
# Name                    Version                   Build  Channel
keras                     2.4.2                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
(base) ziqianwanglive.cn@11:~$ conda list tensorflow
# packages in environment at /Users/ziqianwanglive.cn/opt/anaconda3:
#
# Name                    Version                   Build  Channel
tensorflow                2.2.0                    pypi_0    pypi
tensorflow-estimator      2.2.0                    pypi_0    pypi
